language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3=^8.0 UNIT_TESTS=yes PHP_LINT=yes
    - php: 7.1
      env: TYPO3=^7.6 UNIT_TESTS=yes
    - php: 7.0
      env: TYPO3=^8.0 UNIT_TESTS=yes PHP_LINT=yes
    - php: 7.0
      env: TYPO3=^8.0 CODE_ANALYSIS=yes
    - php: 7.0
      env: TYPO3=^7.6 UNIT_TESTS=yes
    - php: 7.0
      env: TYPO3=^7.6 CODE_ANALYSIS=yes
    - php: 7.0
      env: TYPO3=^6.2 CODE_ANALYSIS=yes
    - php: 5.6
      env: TYPO3=^7.6 UNIT_TESTS=yes PHP_LINT=yes
    - php: 5.6
      env: TYPO3=^6.2 UNIT_TESTS=yes
    - php: 5.5
      env: TYPO3=^7.6 UNIT_TESTS=yes PHP_LINT=yes
    - php: 5.5
      env: TYPO3=^6.2 UNIT_TESTS=yes
    - php: 5.4
      env: TYPO3=^6.2 UNIT_TESTS=yes PHP_LINT=yes
    - php: 5.3
      env: TYPO3=^6.2 UNIT_TESTS=yes PHP_LINT=yes

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require typo3/cms="$TYPO3"
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    if [ "$CODE_ANALYSIS" == "yes" ]; then
      travis_fold start before_phpstan;
      travis_time_start;
      echo "Running php static analysis";
      git clean -dffx;
      composer require typo3/cms="$TYPO3" phpstan/phpstan="^0.6" --ignore-platform-reqs;
      git checkout composer.json;
      travis_time_finish;
      travis_fold end before_phpstan;
      echo;
      echo;
      .Build/bin/phpstan analyse --level 5 ext_localconf.php Classes Tests;
    fi

  - >
    if [ "$UNIT_TESTS" == "yes" ]; then
      echo;
      echo "Running unit tests";
      echo;
      echo;
      .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/;
    fi

  - >
    if [ "$PHP_LINT" == "yes" ]; then
      echo;
      echo "Running php lint";
      echo;
      echo;
      find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
    fi
